In [29]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

data = pd.read_csv("Iris Two Class Data.csv")

print(type(data))


<class 'pandas.core.frame.DataFrame'>


In [30]:
#Check number of classes
classes = data["Class"].nunique()
print(classes)

2


In [31]:
#Check for imbalanced dataset - number of rows for each class
num_classes = data["Class"].value_counts()


print(num_classes)


1    50
0    50
Name: Class, dtype: int64


In [32]:
#Check if there is any missing value in each of the columns.
for col in data.columns:
    print(data[col].isnull().values.any())
    

False
False
False
False
False


In [33]:
print(data.describe())

            Class  sepal-length  sepal-width  petal-length  petal-width
count  100.000000    100.000000   100.000000    100.000000   100.000000
mean     0.500000      5.797000     3.201000      3.507000     1.136000
std      0.502519      0.945319     0.417906      2.095221     0.918114
min      0.000000      4.300000     2.200000      1.000000     0.100000
25%      0.000000      5.000000     3.000000      1.500000     0.200000
50%      0.500000      5.700000     3.200000      3.200000     1.000000
75%      1.000000      6.500000     3.425000      5.525000     2.000000
max      1.000000      7.900000     4.400000      6.900000     2.500000


In [34]:
Xdata_ = np.array(data.iloc[:,1:])
#Data Normalization - ZScore vs MinMax
#MinMax
scaler = preprocessing.MinMaxScaler()
scaler.fit(Xdata_)
new_data = scaler.transform(Xdata_)
print(new_data[0])
print(type(new_data))

[0.55555556 0.31818182 0.77966102 0.70833333]
<class 'numpy.ndarray'>


In [35]:
Xdata = np.array(data.iloc[:,1:])
#Data Normalization - ZScore vs MinMax
#ZScore
scaleer = preprocessing.StandardScaler()
scaleer.fit(Xdata)
newdata = scaleer.transform(Xdata)
print(newdata[0])

[ 0.53477633 -0.72388613  1.0039725   0.72686519]


In [36]:
#MinMax
new_data = pd.DataFrame(data=new_data)

mtrain_data = new_data.iloc[:,:]
mtrain_data_y = data.iloc[:,0]


In [37]:
#ZScore
newdata = pd.DataFrame(data=newdata)

ztrain_data = newdata.iloc[:,:]
ztrain_data_y = data.iloc[:,0]


In [38]:
from sklearn.model_selection import train_test_split

mX_train,mX_test,my_train,my_test = train_test_split(mtrain_data,mtrain_data_y,test_size = 0.30)


In [39]:
from sklearn.neural_network import MLPClassifier


mlpmodel = MLPClassifier(hidden_layer_sizes=(6,),activation='relu',solver='adam',alpha=0.0001,max_iter=200)

mlpmodel.fit(mX_train,my_train)

/home/andmerc/Thesis/Project/cv/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(6,))

In [40]:
predicted = mlpmodel.predict(mX_train)

In [41]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score,roc_auc_score

print(confusion_matrix(my_train,predicted))
#print(classification_report(my_train,predicted))
print(accuracy_score(my_train,predicted))

[[ 1 32]
 [ 0 37]]
0.5428571428571428


In [42]:
predicted_ = mlpmodel.predict(mX_test)
preds = mlpmodel.predict_proba(mX_test)
preds = preds[:,0]

print('-----------Confusion Matrix --------------')
print(confusion_matrix(my_test,predicted_))
print('-----------Classification Report----------')
print(classification_report(my_test,predicted_))
print('-----------Accuracy Score-----------------')
print(accuracy_score(my_test,predicted_))
print('----------------AUC-----------------------')
print(roc_auc_score(my_test,preds))

-----------Confusion Matrix --------------
[[ 0 17]
 [ 0 13]]
-----------Classification Report----------
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        17
           1       0.43      1.00      0.60        13

    accuracy                           0.43        30
   macro avg       0.22      0.50      0.30        30
weighted avg       0.19      0.43      0.26        30

-----------Accuracy Score-----------------
0.43333333333333335
----------------AUC-----------------------
0.23981900452488691


/home/andmerc/Thesis/Project/cv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## One
#####One
